server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testmybatis?serverTimezone=UTC
    password: root
    username: root

#mybatis:

#  config-location: classpath:mybatis-config.xml
